[DependsOn] Support for multiple expressions per query
exadel-inc/aem-authoring-toolkit pull request #121
Opened 2021-01-13 11:19 UTC by ala-n

Add ability to escape ';' character via '\;' to be considered as js operator (instead of DependsOn instance separate configuration)

2021-01-13 11:36 UTC, YanaBr approved these changes

2021-01-13 13:39 UTC, liubou-masiuk requested changes
Hi @ala-n ! 
Unfortunately, currently, this functionality does not work properly
1) ';' is not supported if there is only one `@DependsOn` annotation (probably you also need to escape ';' in `handleDependsOn` method as well)
2) the escaped string should look like this: `\\\\;`
3) if we intend to let clients use ';' as a separator for multiline expressions, we need to agree on the syntax:
     - IIFE (already supported)
     - some other special semantics that lets the users omit the IIFE wrapper

2021-01-13 14:24 UTC, smiakchilo approved these changes

2021-01-13 14:24 UTC, smiakchilo commented on ui.apps/src/main/content/jcr_root/apps/authoring-toolkit/depends-on/README.md
> +DependsOn Query is considered as single expression.
I would put it this way:
`DependsOn query is always treated as a single JavaScript expression, and never as multiple statements in one line. Semicolon symbols (";") within a DependsOn query must be escaped. If you add a query via a Java annotation semicolons escaped automatically..... But if you write directly to XML or HTML you should escape them by hand.....
If you actually need to execute several JavaScript statements within a DependsOn, you can do this by wrapping them in a function call..... Mind that it is still better to move complex structures to a standaline client library`

2021-01-13 20:16 UTC, liubou-masiuk approved these changes

2021-01-16 15:28 UTC, smiakchilo approved these changes

2021-01-16 15:28 UTC, merged