[EDMTP- 248] Add accordion, add select options to branch
exadel-inc/aem-authoring-toolkit pull request #70
Opened 2020-06-16 11:26 UTC by ldzmitrenka

2020-06-24 12:27 UTC, lexastef commented on README.md
> +    accordionTabs = {
Isn't it a standalone component?

2020-07-04 22:10 UTC, liubou-masiuk commented
Hi, @ldzmitrenka, a couple of concerns:
**1) (critical) Functionality.** 
- `variant`, `margins` and `multiple` don't seem to work at all. I don't see them anywhere in XML.
- properties mentioned above need to be specified for the whole accordion, not each panel.
- there is no ability to specify `active` or `disabled` properties which are mentioned in the spec

**2) Naming.** I suggest renaming `accordionTabs` to `accordions` or `accordionPanels` and `@PlaceOnAccordion` to `@PlaceInAccordion`
**3) Validation.** Сurrently, the user can specify both `tabs` and `accordionTabs`, and use both `@PlaceOnAccordion` and `@PlaceOnTab` annotations. However, only accordions are rendered in this case. Maybe it makes sense to add some kind of validation to warn the user?
**4) DependsOn.** there is no ability to conditionally hide accordion panels with dependsOn. Seems like we need something like `DependsOnPanel`. Probably this can be done in a separate ticket. @smiakchilo, @lexastef, what do you think?

2020-09-24 19:20 UTC, Alexey-Chernyakov commented on aem-authoring-toolkit-api/src/main/java/com/exadel/aem/toolkit/api/annotations/container/PlaceOn.java
> +     * String equal to appropriate {@link Accordion#title()} value or {@link Tab #title()}
redundant space

2020-09-25 14:57 UTC, Alexey-Chernyakov requested changes
I think we must do something with _com.exadel.aem.toolkit.core.handlers.container.AccordionHandler_ and _com.exadel.aem.toolkit.core.handlers.container.TabsHandler_.
Actually, they do the same work, but with different annotations.
We need to make a kind of AbstractContainerHandler.

2020-10-08 08:25 UTC, closed without merging